timezone: Europe/Paris
highlighter: pygments
markdown: redcarpet
permalink: /post/:title

redcarpet:
  extensions: [autolink]

exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]

paginate: 5
paginate_path: '/blog/:num'

excerpt_separator: "\n\n\n"

# own settings
name: home
domain: david-dahan.com
url: http://www.david-dahan.com
description: Portfolio website of David Dahan
author:
    name: David Dahan
    github_link: https://github.com/ddahan
    stackoverflow_link: http://stackoverflow.com/users/2255491/
    linkedin_link : http://fr.linkedin.com/in/daviddahanepita/
